id = "pkl"
name = "Pkl"
version = "0.3.0"
schema_version = 1
authors = ["moshyfawn <email@moshyfawn.dev>"]
description = "Pkl language support for Zed"
repository = "https://github.com/Moshyfawn/pkl-zed"

[grammars.pkl]
repository = "https://github.com/apple/tree-sitter-pkl"
commit = "ac58931956c000d3aeefbb55a81fc3c5bd6aecf0"

[language_servers.pkl]
name = "Pkl LSP"
language = "Pkl"
