id = "pkl"
name = "Pkl"
version = "0.1.0"
schema_version = 1
authors = ["moshyfawn <email@moshyfawn.dev>"]
description = "Pkl language support for Zed"
repository = "https://github.com/Moshyfawn/pkl-zed"

[grammars.pkl]
repository = "https://github.com/apple/tree-sitter-pkl"
commit = "9fd989acb67b66799f1fd8168b7386b78a9cdba0"
